### ISSUE TITLE
crc32 查表法制表，多项式使用 0x104c11db7，为什么 hash 表前两位没有碰撞？

### ISSUE THREAD

**Issue by ghost** [221294583/crc32#1]
python crc32 查表法制表，生成的表没有碰撞我可以理解，毕竟只要多项式二进制开头和结尾是 1，那么不同的原始数据得到的 hash 是不同的，但是为什么 hash 表前两位没有碰撞？多项式的前四位是 04c1，04的二进制结尾不是 1，按理说 hash 表前两位应该有碰撞啊

**Comment by 221294583** [comment]
那个104c11db7最一开始那个1是我为了方便写程序补位用的，要不然这个算子对齐起来很麻烦。实际上有用的算子只有04c11db7
